version: "3.8"

services:
  postgres:
    image: postgres
    container_name: online_marketplace_db
    volumes:
      - postgres_vol:/data/db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
  app:
    image: simplemarket
    build: .
    container_name: simple_online_marketplace
    ports:
      - "8080:8080"
    depends_on:
      - postgres
volumes:
  postgres_vol: